### ISSUE TITLE
Operation could not be completed

### ISSUE THREAD

**Issue by haveamission** [panz3r/react-keycloak#12]
I am trying to use this in a Cordova application, and when trying to use it in what seems to be a fairly standard use-case, I am getting:

"The operation could not be completed" and it is trying to access a file:// url

Now I was able to get the actual Keycloak library working in iOS, so I feel there must be something here that is breaking it.

**Comment by haveamission** [comment]
This was related to http://lists.jboss.org/pipermail/keycloak-user/2017-July/011109.html

Apparently when in a compiled project, you need to set the parameter url instead of auth-server-url in your configuration

**Comment by panz3r** [comment]
Hi @haveamission ,
Thanks for your feedback.

Did you managed to solve the error by following the steps in the provided link?

**Comment by haveamission** [comment]
Yes, it fixed the issue.
