### ISSUE TITLE
Redirect uri does not contain `?` and hits an un-known page in React Router 

### ISSUE THREAD

**Issue by ieugen** [panz3r/react-keycloak#13]
Hello,

This might not be the best place to fix this issue but it might prove to be ok. 

I have a create-react-app with React Router and Keycloak.

-> https://localhost:3000/#/ -> 
The application starts and Keycloak is initialized and I get an error like bellow:

```
Page not found /&state=84ee0efb-a7d7-476c-bca0-178d78e5a7ea&session_state=4fb7590d-a969-49e1-b64b-2edafec255f9&code=13467506-aba7-412a-b207-0740fefdbde1.4fb7590d-a969-49e1-b64b-2edafec255f9.3cde65e3-4ef8-482a-ab9e-cf94940ac442
```
NOTE: I have a PageNotFound route that catches all pages without a route . 

I've checked and the request to keycloak server is made with these parameters:

````
redirect_uri | https://localhost:3000/#/
````

So naturally, the server replies with: 

```
location: https://localhost:3000/#/&state=8bfa2824-6bba-4f5d-8604-09280da37843&session_state=4fb7590d-a969-49e1-b64b-2edafec255f9&code=9f8e02cd-bf36-4d64-8f3c-a1ebeb4c990c.4fb7590d-a969-49e1-b64b-2edafec255f9.3cde65e3-4ef8-482a-ab9e-cf94940ac442
```

I believe the redirect_uri should append query param marker `?` or something ? 
Again, not sure if this is the best place to solve this issue.

**Comment by panz3r** [comment]
Hi @ieugen ,

This seems more of a `keycloak` issue to me.

What parameters are you passing as `initConfig` prop and are you calling `keycloak.login()` somewhere In your code?

**Comment by ieugen** [comment]
Hi, 

I am using defaults and I am not calling keycloak.login() in my code. I believe I have fixed it by moving KeycloakProvider from top level to inside the router, like bellow:

This way, I believe keycloak gets the call before react router and it can handle it before it bubbles up. It seems to work so far.

```
const Main = ({ store, client, keycloak }) => (
  <Provider store={store}>
    <ApolloProvider client={client}>
      <IntlProvider locale="en" messages={defaultMessages}>
        <Router key="mainRouter">
          <KeycloakProvider keycloak={keycloak} initConfig={initConfig}>
            <Index />
          </KeycloakProvider>
        </Router>
      </IntlProvider>
    </ApolloProvider>
  </Provider>
);
```

**Comment by ieugen** [comment]
It seems that the issue is persisting.

It seems it is related to HashRouter. I've switched to html5 push state router and I don't get the error page no more.

**Comment by panz3r** [comment]
Hi @ieugen ,

Sorry for the late answer.

Could you please try using the `sample` app available on [`react-router`](https://github.com/panz3r/react-keycloak/tree/react-router) branch.

I made some testing with `react-router` and could not reproduce the issue (using both `HashRouter` and `BrowserRouter`).

**Comment by ieugen** [comment]
Hi, I would love to but I am swamped right now. Anyway, I've moved past it since we are using pushState so I think we can close the issue for now ?!

**Comment by panz3r** [comment]
Ok, thanks for your feedback.

**Comment by FabianPiconeDev** [comment]
I had a similar Problem. It has something to do with the HashRouter and the redirection.

I am using silent check-sso.

* When I have an active user session, and I directly open a private route (http://localhost:3000/#/user/foo/bar), keycloak.init() triggers the silent sso check and I remain on my private route.
* When I have **not** an active user session, and I directly open a private route (http://localhost:3000/#/user/foo/bar), keycloak.init() does a hard reload on http://localhost:3000/#/user/foo/bar&error=login_required&state=133226a6-7138-4aa5-87c1-4f12dd1e18d5 , the url automatically changes to http://localhost:3000/#/user/foo/bar but no route is matching with the url.

When I change the router from HashRouter to BrowserRouter, the route on scenario with a **non** active session matches as expected.

Any ideas for the issue with the HashRouter?

**Comment by borivojevic** [comment]
Setting responseMode to "query" in initConfig like

```
const keycloakInitOptions: KeycloakInitOptions = {
    checkLoginIframe: false,
    redirectUri: window.location.origin,
    responseMode: 'query',
  };
```

tells server use query string rather than a hash in redirect url.
