### ISSUE TITLE
Are you supposed to be able to log on automatically with this library?

### ISSUE THREAD

**Issue by haveamission** [panz3r/react-keycloak#14]
I am trying to pass my tokens and check-sso, but for some reason, I am not logging in automatically.

Is there a way to do so? Should passing in tokens theoretically do it? Because I am not triggering the onAuthSuccess event at all

**Comment by panz3r** [comment]
Hi @haveamission ,

Can you please check if the logic of the demo app supplied with this library works for your use case?

I made some tests using it and by keeping the tokens saved into `localStorage` I can see the `onAuthSuccess` event being triggered successfully.
