### ISSUE TITLE
Sourcemap warnings when building for webpack 5

### ISSUE THREAD

**Issue by mario-subo** [panz3r/react-keycloak#179]
**Describe the bug**
It's a build warning 

**To Reproduce**
- Setup and project with CRA 5 (Webpack 5) and import any component from `@react-keycloak/web`
- Run build or start
- See the warning in the console

**Expected behavior**
no sourcemap warnings should appear

**Screenshots**
`WARNING in ./node_modules/@react-keycloak/web/lib/withKeycloak.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\XXXXXXXX\node_modules\@react-keycloak\web\lib\@react-keycloak\web\withKeycloak.tsx' file: Error: ENOENT: no such file or directory, open 'C:\XXXXXXXXI\node_modules\@react-keycloak\web\lib\@react-keycloak\web\withKeycloak.tsx'`

- OS: Windows 
- Browser: Chrome

**Comment by mario-subo** [comment]
duplicate of re #176

**Comment by gnowland** [comment]
I submitted a PR to fix this https://github.com/react-keycloak/react-keycloak/pull/200
