### ISSUE TITLE
Browser Automatically logout after 5s of logging in

### ISSUE THREAD

**Issue by springADAM** [panz3r/react-keycloak#183]
i have my app function like this
`function App() {
  return (
    <ReactKeycloakProvider authClient={keycloak}>
      <div className="App">
        <Router>
          <Navbar />
          <Routes>
            <Route
              path="/"
              element={
                <PrivateRoute>
                  <HomePage />
                </PrivateRoute>
              }
            />
          </Routes>
        </Router>
      </div>
    </ReactKeycloakProvider>
  );
}`
browser automatically loggout after 5s of logging in

**Comment by springADAM** [comment]
it seems that when i refresh it doesn't require me to login but also loses the scope that i logged in after 5s

**Comment by junjou** [comment]
If you are on Firefox you can try to reduce the cookie policy from strict to standard.

**Comment by andrecastelo** [comment]
I had an issue like this as well - we solved it by allowing the url used by the iframe check to be publicly accessible. So if anyone ever runs into this again, check if the URL loaded by the iframe is not blocked for some reason (CORS and iframe policy might also apply).

The 5 seconds is basically the default duration of `checkLoginIframeDuration`. If you disable that with `checkLoginIframe: false` in the init options, then it's also fixed, but not recommended.
