### ISSUE TITLE
Request for support of confidential clients

### ISSUE THREAD

**Issue by BigBallard** [panz3r/react-keycloak#189]
**Is your feature request related to a problem? Please describe.**
Not due to a bug or problem

**Describe the solution you'd like**
We are wanting to use a confidential keycloak client to build out an internal tool. It appears however this library does not support that since we get a 401 response after being redirected back to the app after a successful login. A call is made to the token endpoint and the following response is received:
```
error: "unauthorized_client"
error_description: "Client secret not provided in request"
```
Since the client is confidential, the keycloak calls would need the client secret, which doesnt seem to be the case. I have switched the client to public to make sure it's not just my configuration and that did work, switching back to confidential yielded the same error. 

**Describe alternatives you've considered**
I have tried explicitly setting the clientSecret of the keycloak instance created before passing to the `ReactKeycloakProvider` but that didn't yield any success.

**Additional context**
Snippets:
```jsx
const url = import.meta.env.VITE_KEYCLOAK_URL
const realm = import.meta.env.VITE_KEYCLOAK_REALM
const clientId = import.meta.env.VITE_KEYCLOAK_CLIENT_ID
const clientSecret = import.meta.env.VITE_KEYCLOAK_CLIENT_SECRET

const config = {
  url,
  realm,
  clientId
} as KeycloakConfig

const keycloak = new Keycloak(config)
keycloak.clientSecret = clientSecret

export default keycloak

...

<ReactKeycloakProvider
  authClient={keycloak}
  initOptions={{
    onLoad: "login-required",
    checkLoginIframe: true,
    autoRefreshToken: true
  }}
>
```

**Comment by Bessonov** [comment]
Why do you want to use a confidential client? Everyone can extract the secret. Because of that neither it is supported nor it should be supported.

**Comment by BigBallard** [comment]
Ya I guess I really didn't think about the secret being sent with the request, that was a face palm moment.... I think I was stuck in server mindset and got my thought processes mixed up. Closing.
