### ISSUE TITLE
redirectUri not trigger after login successful

### ISSUE THREAD

**Issue by thaind97git** [panz3r/react-keycloak#195]
**Describe the bug**
When I login successful, the browser will redirect to `"/"`, not the specific URI that I have declared as an argument inside login function

```js
const onClickLogin = () => {
  keycloak.login({ redirectUri: `http://localhost:3000/dashboard` })
}
```
For this code, after login is successful, the browser redirect to `"/"` instead `"/dashboard"`

**Expected behavior**
Can redirect a specific URI after login successful

**Comment by Castels88** [comment]
sucaterla tutti
