### ISSUE TITLE
Token not being refreshed

### ISSUE THREAD

**Issue by aminmc** [panz3r/react-keycloak#21]
I have the following code:

```js
initConfig={{
                          onLoad: 'login-required'
                      }}
```
And using the following in places where I need to make an API call:

```js
const [keycloak] = useKeycloak();
....
keycloak.token used in Axios call
```
However I'm noticing that the token isn't being automatically refreshed.  Do I need to register something in:

```js
onTokens={(tokens) => {
  Do something in here? Set the token in keycloak?
}}
```

**Comment by panz3r** [comment]
Hi @aminmc ,

> Do I need to register something in:
> ```
> onTokens={(tokens) => {
>  Do something in here? Set the token in keycloak?
> }}

No, you don't need to use this handler unless you need to export `Keycloak` tokens outside (such as in the case of storing them).

> And using the following in places where I need to make an API call:
> ```
> const [keycloak] = useKeycloak();
> ....
> keycloak.token used in Axios call

How are you passing the token to `axios`? Are you using a callback?

**Comment by aminmc** [comment]
hi @panz3r 

I do something like this:

```js
const [keycloak] = useKeycloak();

    //create axios instance

    instance.interceptors.request.use(async (config) => configureAxios(config, keycloak),
        (err) => {
            return Promise.reject(err);
        });
```
and set header config with
```js
 config.headers['Authorization'] = `Bearer ${keycloak.token}`;
```

**Comment by panz3r** [comment]
Hi @aminmc ,

I made a quick test implementation for your case, I implemented a `useAxios` hook that handles tokens with Keycloak and I can confirm it to work as expected.

```js
const useAxios = baseURL => {
  const [axiosInstance, setAxiosInstance] = useState({});
  const [keycloak, initialized] = useKeycloak();

  useEffect(() => {
    const instance = axios.create({
      baseURL,
      headers: {
        Authorization: initialized ? `Bearer ${keycloak.token}` : undefined,
      },
    });

    setAxiosInstance({ instance });

    return () => {
      setAxiosInstance({});
    };
  }, [baseURL, initialized, keycloak, keycloak.token]);

  return axiosInstance.instance;
};
```

And you use like this
```js
  const axiosInstance = useAxios('https://jsonplaceholder.typicode.com');
  const callApi = useCallback(() => {
    axiosInstance.get('/todos/1');
  }, [axiosInstance]);
```

Notice that I'm using a `useEffect` hook inside the `useAxios` one, this is done to allow React to re-create the `axios` instance with the new `keycloak.token` as it changes otherwise it won't get updated.

Let me know if this helps you.

**Comment by aminmc** [comment]
@panz3r thanks for your feedback, I actually have something like this:

```js
const useApiRequest = (path, {verb = 'get', params = {}} = {}) => {
    const [state, dispatch] = useReducer(reducer, initialState);
    const instance = axios.create();
    const [keycloak] = useKeycloak();

    instance.interceptors.request.use(async (config) => configureAxios(config, keycloak),
        (err) => {
            return Promise.reject(err);
        });

    const makeRequest = async () => {
        dispatch(executing());
        let response;
        try {
            response = await instance[verb](`${envContext.url}${path}`, params);
            dispatch(success(response));
        } catch (err) {
            console.log(err.stack);
            if (axios.isCancel(err)) {
                console.log(err.message);
            } else {
                dispatch(error(err.response, err));
            }
        }
    };

    return [state, makeRequest];
};
```
I pass the keycloak into the configure axis method. Am I right in thinking that keycloak.token might be an expired token?

**Comment by aminmc** [comment]
actually I might have been mistaken and I can see the token being refreshed and correctly being passed into the useApiRequest. Unless you have any objections I might close this issue.

**Comment by panz3r** [comment]
Hi @aminmc ,

> actually I might have been mistaken and I can see the token being refreshed and correctly being passed into the useApiRequest. Unless you have any objections I might close this issue.

I'm glad to hear that. 

I'm closing the issue. Thanks again for your feedback.
