### ISSUE TITLE
Login return

### ISSUE THREAD

**Issue by victor-palca** [panz3r/react-keycloak#24]
I am trying to make an event after the login call, but it does not respond .success, .then. Can anyone help me?

Code:
  function loginKeycloak () {
    keycloak.login().success(() => {
      console.log('here')
    }).error(() => {
      console.log('error')
    })
  }

**Comment by panz3r** [comment]
Hi @vihpalca ,

As per `Keycloak` documentation ([here](https://www.keycloak.org/docs/latest/securing_apps/index.html#login-options)) the `login` call does not return a `Keycloak Promise` so you cannot use it like that.

If you need to intercept a successful authentication event you need to attach an event listener and handle the event there.
```js
onKeycloakEvent = (event, error) => {
  console.log('onKeycloakEvent', event, error);
  // Check for onAuthSuccess event
}
...
<KeycloakProvider onEvent={onKeycloakEvent}>
...
</KeycloakProvider>
```

Let me know if this helps you.
