### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by panz3r** [panz3r/react-keycloak#29]
**Is your feature request related to a problem? Please describe.**
A set of unit tests is currently implemented using `Jest` on this project but `code coverage` is not working as intended (report does not show covered code lines, etc.).

**Describe the solution you'd like**
Code coverage report working and possible integration with [`Coveralls`](https://coveralls.io).

**Comment by arnabk** [comment]
@panz3r Please assign me this task and I can send your PR for coverall integration

**Comment by arnabk** [comment]
@panz3r The PR is ready. However it is failing because coveralls is not finding any settings for the repository. You have to create the conf under your account and merge this PR to see the results. I tested with my account and it is working fine. I reported the coverage details in PR.
