### ISSUE TITLE
Add caching to Provider

### ISSUE THREAD

**Issue by betheny-carmani** [panz3r/react-keycloak#3]
### Problem
When the Provider from `react-keycloak` is used across multiple unconnected modules, and multiple such modules are used on the same page, multiple Keycloak instances try to initialize themselves after one another, creating a refresh deadlock.
### Solution
A caching functionality should be added to the Provider that checks for available Keycloak data in the local storage prior to initialization, and stores retrieved data following the initialization. The storage key should be identified by a prop (e.g. `cacheKey`); an undefined or null `cacheKey` indicates that no caching should be used.

**Comment by panz3r** [comment]
Hi @betheny-carmani ,

Could you please clarify the context of this issue.
I can't figure an use case where you'd need to have more than on `Provider` in an app.

**Comment by betheny-carmani** [comment]
@panz3r it's multiple apps that run within a larger framework, where both have no access to any other component. In my specific case, its multiple React-based macros for Atlassian Confluence. The macros can be used by any user so it is likely that two macros using `react-keycloak` appear on the same page. When this is the case, the faster one redirects to Keycloak, returns to the page and is initialized, then the other one does the same, wherein the former becomes uninitialized again, restarting the process.

**Comment by panz3r** [comment]
Hi @betheny-carmani ,

Using the newly published `6.0.3` version of `react-keycloak`, you should be able to handle this use case and implement caching as follow
```js
const keycloak = new Keycloak();

class PersistedApp extends React.Component {
  constructor(props) {
    super(props);
    this.tokens = JSON.parse(localStorage.getItem('kcTokens') || '{}');
  }

  onKeycloakTokens = tokens => {
    localStorage.setItem('kcTokens', JSON.stringify(tokens));
  }

  render() {
    return (
      <KeycloakProvider
        keycloak={keycloak}
        initConfig={{
          onLoad: 'check-sso',
          ...this.tokens,
        }}
        onTokens={this.onKeycloakTokens}
      >
        [Your Module Here]
      </KeycloakProvider>
    );
  }
}
```

Let me know if this helps with your issue.

**Comment by betheny-carmani** [comment]
It got me a step further but unfortunately, time is still not on my side: App1 tries to init, page refreshes (because I use Kerberos I don't need to type in my credentials here), App1 inits again, acknowledges that it was just inited, but before the caching function is called, App2 tries to init, refreshing the page and thus uniniting App1, restarting the cycle. Reading further into this I'm not sure whether it is possible to do it either way. Unless you have any additional ideas, I will have to find another way around it.

**Comment by panz3r** [comment]
Hi @betheny-carmani ,

Unfortunately I don't have any other idea about your issue.
I'd suggest you to try using `keycloak-js` directly and check if your use-case is supported, if it is, let me know so that we can find a way to improve `react-keycloak`.
