### ISSUE TITLE
TypeError: kc.updateToken(…).success is not a function in react 16.9.0

### ISSUE THREAD

**Issue by amir-christian** [panz3r/react-keycloak#34]
**What is wrong?**

Details here.
https://stackoverflow.com/questions/58436689/react-keycloak-typeerror-kc-updatetoken-success-is-not-a-function

I think that react-keycloak using the "old" .success() method.
I'm using the package from https://www.npmjs.com/package/react-keycloak.

**Expected behavior**

No Errors

**Environment**

 - OS: Windows 10
 - Browser: Chorme 77
 - Version: react-keycloak 6.1.0

**Comment by panz3r** [comment]
Hi @amir-christian ,

It seems that this is an issue with `keycloak-js` itself and it is set to be released with version `8.0.0` of `keycloak-js`.

Also `react-keycloak` is not using `.success()` internally.

See here for more details about the issue [KEYCLOAK-8938](https://issues.jboss.org/browse/KEYCLOAK-8938).

In the meantime I'd suggest you to avoid using `promiseType: 'native'` in your setup.

**Comment by jonkoops** [comment]
This should be fixed in Keycloak 8+. It's reccomended to use `promiseType: 'native'` [whereever possible.](https://www.keycloak.org/docs/latest/securing_apps/#a-note-about-code-promisetype-code)
