### ISSUE TITLE
Support kc_idp_hint

### ISSUE THREAD

**Issue by strowk** [panz3r/react-keycloak#35]
**Is your feature request related to a problem? Please describe.**
Keycloak supports kc_idp_hint parameter for login flow (see https://www.keycloak.org/docs/latest/server_admin/index.html#_client_suggested_idp).
Keycloak.js has method createLoginUrl, which receives idpHint, but it seems that react-keycloak builds login url without using createLoginUrl and there is no possibility to pass idpHint

**Describe the solution you'd like**
KeycloakProvider should receive hint and use it when building login url, where user is redirected to.

**Describe alternatives you've considered**
Currently I configure default provider for realm in 'Browser' flow (see https://www.keycloak.org/docs/latest/server_admin/index.html#default_identity_provider).
That works, but I would like to use hint instead, so that I could login using internal users, while debugging. Current approach means that login is always performed by broker idp.

**Comment by panz3r** [comment]
Hi @strowk ,

Currently the `KeycloakProvider` component accept the `initConfig` prop which contains the config which gets passed to `keycloak.init` method, so if `keycloak.init` supports this option you can pass it inside the `initConfig` prop.

If that's not supported you can try the following setup, in the `initConfig` prop be sure to pass as `onLoad` the value `check-sso` (which is the default), and then in your login screen you can invoke the `login` method of `keycloak` passing the `idpHint` option as you need (you can retrieve the `keycloak` instance by using either the `withKeycloak` HOC or the `useKeycloak` hook).

Let me know if this helps you.

**Comment by strowk** [comment]
I don't really want to switch from `login-required` to `check-sso` to manually implemented same thing. But I see now that this is a wrong place to ask for support of hint in `initConfig`.

I wanted to create issue in keycloak itself, but people there does not seem to be interested in supporting it - https://issues.jboss.org/browse/KEYCLOAK-4225 .
