### ISSUE TITLE
silentCheckSsoRedirectUri breaks react behaviour in Gatsby project

### ISSUE THREAD

**Issue by orelmax** [panz3r/react-keycloak#36]
**Describe the bug**
Enabling `silentCheckSsoRedirectUri` option in very basic Gatsby project breaks react's expected behaviour in a way, that all child components which are using `useContext` or `withKeycloak` won't ever get updated properties.

**To Reproduce**
1. I've created repo to reproduce the issue [here](https://github.com/orelmax/react-keycloak-demo-issue) (infrastructure isn't included)
2. Configure keycloak
3. Open localhost:8000
4. 'getting ready...' will never disappear

**Expected behavior**
State is expected to be updated after keycloak initialized

**Desktop (please complete the following information):**
 - OS: macOS catalina 10.15.1
 - Browser chrome
 - Version 79

**Additional context**
Without `silentCheckSsoRedirectUri` everything works as expected.  
Also problem isn't occuring in simple CRA project.

**Comment by panz3r** [comment]
Hi @orelmax ,

I opened a PR to your demo to fix the reported issue.

Since no change is required to `react-keycloak` itself, I'm going to close this issue.
If you need further help just comment the linked PR.

**Comment by orelmax** [comment]
@panz3r thanks a lot for pointing out to this solution!
