### ISSUE TITLE
Cannot find name 'ReactKeycloakContextValue'

### ISSUE THREAD

**Issue by jannes-io** [panz3r/react-keycloak#37]
**Describe the bug**
Typescript compile error

**To Reproduce**
1. Compile with typescript

**Expected behavior**
No errors happen

**Additional context**
full error message:
`node_modules/@react-keycloak/web/index.d.ts(120,5): error TS2304: Cannot find name 'ReactKeycloakContextValue'.`

using:
@react-keycloak/web: ^1.0.0-alpha.5
keycloak-js: ^8.0.1,
npm: 6.13.4
tsc: 3.7.3

**Comment by jannes-io** [comment]
@panz3r ,

Created a new PR with the suggested changes (had some issues on my side rendering me unable to edit the original PR).

It'd be great if it could be fixed and released soon. We rely on react-keycloak in production and it's currently causing deploys to fail across multiple projects where we recently migrated from the deprecated package to this monorepo

**Comment by panz3r** [comment]
Hi @jannes-io ,

Version `1.0.0-alpha.6` has been released.

Thanks again for your feedback and contribution.
