### ISSUE TITLE
Add types

### ISSUE THREAD

**Issue by betheny-carmani** [panz3r/react-keycloak#4]
### Problem
When using `react-keycloak` in TypeScript, the package's types cannot be resolved.
### Solution
A TypeScript type file, containing the types for the various functions used in the package, should be added to the distribution.

**Comment by panz3r** [comment]
Hi @betheny-carmani ,

Thanks for your feedback, I'll consider adding Typescript definitions to the project

**Comment by betheny-carmani** [comment]
@panz3r Thanks for the addition. However, it seems as though there are a few errors. The KeycloakProvider has no props except for keycloak (so no LoadingComponent, initConfig, ...) and TOriginalProps (line 48) has a syntax error. Could you double-check the types file? Thanks.

**Comment by panz3r** [comment]
Hi @betheny-carmani ,

I just published a new version containing updated TS definitions.
