### ISSUE TITLE
use Keycloak instance with Observables

### ISSUE THREAD

**Issue by panz3r** [panz3r/react-keycloak#40]
Hi @panz3r , I just found this repo and the packages and so far it's working really great!

Would it be possible to expose the keycloak instance directly?
Because currently it is only possible to access the instance via hook or HOC, as far as I can tell.

However I am trying to encapsulate e.g. the userProfile (`keycloak.profile`) via [observable ](https://github.com/BeTomorrow/micro-observables), so that I can manage the logic to check if it is loaded and then load it if needed centrally, and then provide the value via observable.

Again, thank you for the great work!

_Originally posted by @FatalMerlin in https://github.com/panz3r/react-keycloak/issues/27#issuecomment-575804557_

**Comment by panz3r** [comment]
Hi @FatalMerlin,

This issue is not directly related to `react-keycloak` itself but I suppose that you can try to wrap the `Keycloak` instance that is initially passed to `KeycloakProvider`.

So for instance you can have an initialisation file `keycloak.js` like this 
```js
// Setup Keycloak instance as needed
const keycloak = new Keycloak({
...
});

export default keycloak;
```

in the `App.js` (or inside the file where you initialise `KeycloakProvider`)
```js
import { KeycloakProvider } from '@react-keycloak/web';

import keycloak from './keycloak';

// Wrap everything inside KeycloakProvider
const App = () => {
  return <KeycloakProvider keycloak={keycloak}>...</KeycloakProvider>;
};
```

The Keycloak instance exported from `keycloak.js` would be then accessibile from any other file and you can wrap it in an Observable like this (maybe in a file called `rxKeycloak.js`)
```js
import { observable } from "micro-observables";

import keycloak from './keycloak';

const rxKeycloak = observable(keycloak);

export default rxKeycloak;
```

Remember that by doing this you'll need to check the init state and the logged-in state yourself, `react-keycloak` would only call `init` on the  `Keycloak` instance and keep it available to his `HOC` and `Hooks`.

Let me know if this helps you and Thanks again for your feedback.

**Comment by FatalMerlin** [comment]
Hi @panz3r,

Thanks for your quick response!

From my understanding this is not possible using `@react-keycloak/nextjs`, since instead of `KeycloakProvider` you have to use `appWithKeyCloak`.

(Maybe this is where I went wrong 😅)

This is why I added this to the WIP Next.js thread.
Implementing this using the `@react-keycloak/web` bindings would be possible already, as you stated above, but with the Next.js bindings the library completely encapsulates the `keycloak` instance and only provides access via React bindings (HOC or Hook).

My current workaround is to define an empty `observable` which is later initialized by a stub React FC, that waits for `keycloak` to be initialized.

```ts
const KeycloakWrapper: React.FC = () => {
    const [keycloak, initialized] = useKeycloak();

    // wait for keycloak to be initialized
    if (initialized && keycloak) {
        // register onAuthSuccess callback to load the profile once the user logs in
        keycloak.onAuthSuccess = async () => {
            const profile = await keycloak.loadUserProfile();
            // write profile into observable to be used via `useObservable` hook
            writeableUserProfile.set(profile);
            // debug
            console.log('Loaded Profile');
        };

        // register onAuthLogout callback to unload profile information once the user
        // logs out.
        keycloak.onAuthLogout = async () => {
            writeableUserProfile.set(undefined);
        };

        // if the app loads but the user is already authenticated, onAuthSuccess won't fire
        // because the user is not authenticated, instead the existing session is used.
        // therefore we have to manually call our callback.
        if (keycloak.subject) {
            keycloak.onAuthSuccess();
        }
    }

    return <React.Fragment />;
};
```

Additionally I noticed that `this.props.isAuthenticated` seems to be always `undefined`, which is why I'm checking `keycloak.subject`.

Maybe this error is related?

![image](https://user-images.githubusercontent.com/14237330/72667598-cf069880-3a1d-11ea-9988-71ab03b0c064.png)

Maybe this can be resolved by pulling the `keycloak` instance out of `appWithKeycloak` as a singleton that can then be exported to be used by others.

BR

**Comment by panz3r** [comment]
Hi @FatalMerlin ,

> From my understanding this is not possible using @react-keycloak/nextjs, since instead of KeycloakProvider you have to use appWithKeyCloak.

You are right, I though it was unrelated to `nextjs` 😅 .

> Maybe this can be resolved by pulling the keycloak instance out of appWithKeycloak as a singleton that can then be exported to be used by others.

Unfortunately that won't be possible because of the wrapping required to make `keycloak-js` work with `NextJS`.

Reading you code I noticed that you are overriding both `onAuthSuccess` and `onAuthLogout` callback and that would cause issues since they are internally used by `react-keycloak` to handle the instance state.
A better solution I can think of is the following:
```tsx
export const writeableUserProfile = observable(undefined);

const RXKeycloakProvider: React.FC = ({ children }) => {
    const [keycloak, initialized] = useKeycloak();
    // uesEffect will keep `writeableUserProfile` and `keycloak` in sync
    useEffect(() => {
      if (initialized && !!keycloak && keycloak.authenticated) {
        keycloak.loadUserProfile().then(profile => {
          // write profile into observable to be used via `useObservable` hook
          writeableUserProfile.set(profile);
          // debug
          console.log('Loaded Profile');
        });
      } else {
        writeableUserProfile.set(undefined);
      }
    }, [keycloak, keycloak.authenticated, initialized]);

    return React.Children.only(children);
};

export default RXKeycloakProvider;
```

By using the `useEffect` hook you can keep the `keycloak` state in sync with your observable without having to attach the Keycloak listeners.

And then you can wrap your `MyApp` component with it

```tsx
import React from 'react'
import App from 'next/app'

import { appWithKeycloak } from '@react-keycloak/nextjs'

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props
    return (
      <RXKeycloakProvider>
        <Component {...pageProps} />
      </RXKeycloakProvider>
    )
  }
}

export default appWithKeycloak({
  realm: process.env.KEYCLOAK_REALM as string,
  url: process.env.KEYCLOAK_URL as string,
  clientId: process.env.KEYCLOAK_CLIENT_ID as string
})(MyApp
```

I'm going to release a new version with the fixed `PropTypes` soon, thanks again for your feedback, I hope this helps you.

**Comment by FatalMerlin** [comment]
Hi @panz3r ,

thanks, I'll give this a try.

Good to know that the event handlers are used by this library!
Is that in the docs?

**Comment by panz3r** [comment]
Hi @FatalMerlin ,

> Good to know that the event handlers are used by this library!
> Is that in the docs?

That's not actually stated on `@react-keycloak/nextjs` docs, I might add it since it was exposed for the `web` package (as the `onEvent` handler) but not currently available for the `nextjs` package.

Thanks again and let me know.
