### ISSUE TITLE
nextjs: support for LoadingComponent

### ISSUE THREAD

**Issue by pierregm** [panz3r/react-keycloak#42]
Hello,
Awesome library, thanks a lot for the hard work!

I noticed that in `@react-keycloak/nextjs`, the `LoadingComponent` option isn't available to the `KeycloakProvider`: it gets only the keycloak instance and the `onEvent` method.

Would it be possible to add some extra options to `appWithKeycloak` that would be given to the provider ?

**Comment by panz3r** [comment]
Hi @pierregm ,

I just released `@react-keycloak/nextjs` version `1.0.0-alpha.11` which allow passing a new parameter to `appWithKeycloak` with all the `KeycloakProvider` props.
See [README](https://github.com/panz3r/react-keycloak/blob/master/packages/nextjs/README.md) here for more details.

Thanks again for your feedback.
