### ISSUE TITLE
Redirection to Registration Page

### ISSUE THREAD

**Issue by DawerRafi** [panz3r/react-keycloak#46]
**Is your feature request related to a problem? Please describe.**
I am using KeycloakProvider via react-router to authenticate existing users. I made a login component out of the example. I wanted to create a similar component for Registration, yet there is no way to redirect to Registration Page. The KeycloakProvider gives access to initConfigs but if login options were also exposed, I could have simply set action:register and be able to redirect non authenticated users to the KC registraion page.

**Describe the solution you'd like**
Expose login options as props to KeycloakProvider so that users can register and return as authenticated users after the registration completes.

**Comment by panz3r** [comment]
Hi @DawerRafi ,

Thanks for your feedback.

From my understanding what you'd need to do is call the `register` method on the `keycloak` instance.

The updated setup for `LoginPage` would be 
```js
const LoginPage = withRouter(
  withKeycloak(({ keycloak, location }) => {
    const { from } = location.state || { from: { pathname: '/home' } }
    if (keycloak.authenticated) return <Redirect to={from} />

    const login = useCallback(() => {
      keycloak.login()
    }, [keycloak])

    const register = useCallback(() => {
      keycloak.register()
    }, [keycloak])

    return (
      <div>
        <button type="button" onClick={login}>
          Login
        </button>
        <button type="button" onClick={register}>
          Register
        </button>
      </div>
    )
  })
)
```

if you need more info about the `keycloak.register` method just check out the official `Keycloak JS Adapter` doc [here](https://www.keycloak.org/docs/latest/securing_apps/#register-options).

Let me know if this helps you.
