### ISSUE TITLE
NextJS appWithKeycloak caused the page to load twice

### ISSUE THREAD

**Issue by R-Adam9** [panz3r/react-keycloak#48]
Hello @panz3r , i got this bug when i tried to use keycloak to authenticate my NextJS app. i also used the NextJS example that you provided, the same problem happened

**Describe the bug**
when exporting the NextJS _app.js with appWithKeycloak, it caused a second page reload when trying to reload the page or using Router.reload

**To Reproduce**
1. Go to any page
2. Click the browser reload button
3. watch the browser Console, "Navigated to ...." message is logged twice

**Comment by panz3r** [comment]
Hi @R-Adam9 ,

Unfortunately that depends on how Keycloak check for the initial login state when `onLoad` is set to `check-sso`, it does a redirect to `keycloak` and back to the page with the `state` queryparam.

A way to avoid this behaviour is to set the `silentCheckSsoRedirectUri` and set up the page.
See the official Keycloak documentation [here](https://www.keycloak.org/docs/latest/securing_apps/index.html#_javascript_adapter) for more details.

**Comment by agungsb** [comment]
Hi @panz3r ,

Is there anyway to setup the init?

With Keycloak, I could do the following:

```
keycloak.init({
      onLoad: 'check-sso',
      silentCheckSsoRedirectUri: 'http://localhost:3000'}/silent-check-sso',
    })
```

But I don't see any example about how to do it with react-keycloak.

**Comment by panz3r** [comment]
Hi @agungsb ,

To pass options to the `init` method you can use the `initConfig` prop of the `KeycloakProvider` component.

**Comment by kevinswarner** [comment]
I am also experiencing the load-twice issue using a NextJS SSR setup. However, even after I implemented the silentCheckSsoRedirectUri approach, I am still seeing the page load twice. I am using Chrome (Version 86.0.4240.183 (Official Build) (x86_64)). I see that there is a warning in the Keycloak docs about modern browsers possible limiting this feature. How can I tell if that is what is going on or if something else is broken?

I have the following in my _app.js.

```javascript
import * as React from 'react';
import cookie from 'cookie';
import { SSRKeycloakProvider, SSRCookies } from '@react-keycloak/ssr';
import '../styles/globals.css';

const keycloak = {
  url: 'http://KEYCLOAK_SERVER/auth/',
  realm: 'my-realm',
  clientId: 'my-client'
};

const initOptions = {
  onLoad: 'check-sso',
  silentCheckSsoRedirectUri: 'http://localhost:3000/silent-check-sso.html'
};

function MyApp({ Component, pageProps, cookies }) {
  return (
    <SSRKeycloakProvider
      keycloakConfig={keycloak}
      persistor={SSRCookies(cookies)}
      initConfig={initOptions}
    >
      <Component {...pageProps} />
    </SSRKeycloakProvider>
  );
}

function parseCookies(request) {
  if (!request || !request.headers) {
    return {};
  }
  return cookie.parse(request.headers.cookie || '');
}

MyApp.getInitialProps = async context => {
  return {
    cookies: parseCookies(context?.ctx?.req)
  };
};

export default MyApp;
```

And, for the silent html page redirect, I placed the following in the file /public/silent-check-sso.html.

```html
<html>
  <body>
    <script>
      parent.postMessage(location.href, location.origin);
    </script>
  </body>
</html>
```

I appreciate any thoughts you might have. Thank you!

**Comment by BoKKeR** [comment]
I am also facing the same issue, any hints how to fix?

**Comment by vanam** [comment]
https://www.keycloak.org/docs/latest/securing_apps/#_modern_browsers

It seems to be caused by cookie policies in modern browsers. We can turn off the `silentCheckSsoFallback`; however, it is probably not what we want.

**Comment by nvegater** [comment]
I support the notion. Why is this issue closed ?

**Comment by vanam** [comment]
Am I the only one who would avoid Keycloak because of this? It looks like a blocker not a "won't fix".

**Comment by maxgfr** [comment]
Any updates ?

**Comment by vanam** [comment]
I ended up using [next-auth.js](https://next-auth.js.org/) It has a [Keycloak provider](https://next-auth.js.org/providers/keycloak).
