### ISSUE TITLE
Question: Logging in with token/refreshToken

### ISSUE THREAD

**Issue by alcesleo** [panz3r/react-keycloak#50]
I want to log a user in using a token/refreshToken gotten from an API endpoint, without going through the UI steps. 

It seems like the newly added parameter to `appWithKeycloak` should enable this somehow, but so far no success:

```ts
const config: KeycloakConfig = {
  realm: process.env.NEXT_PUBLIC_KEYCLOAK_REALM as string,
  url: process.env.NEXT_PUBLIC_KEYCLOAK_URL as string,
  clientId: process.env.NEXT_PUBLIC_KEYCLOAK_CLIENT_ID as string
};

const initConfig: KeycloakInitOptions = {
  token: "eyJhbGciOiJSUzI1...",
  refreshToken: "eyJhbGciOiJIUzI..."
};

export default appWithKeycloak(config, { initConfig })(App);
```

Any idea how I can go about implementing this with @react-keycloak/nextjs? Am I on the wrong track entirely?

**Comment by panz3r** [comment]
Hi @alcesleo ,

Thanks for your feedback, actually that should work as expected since `keycloak-js` allows you to pass previously obtained tokens to the `init` method (used internally by `react-keycloak`).
Which error are you receiving when trying to pass those params (if any)?

**Comment by alcesleo** [comment]
Hi @panz3r, thank you for your help! 

I thought this should work as well, but I'm getting no errors and it simply behaves as if I'm not logged in at all, subsequently logging in the normal way still works. I'm trying to debug this at the moment.

Even if I do get this to work, is it possible to set something in the `_app.tsx` based on an API request? I'm only trying to hard code in a token at this point but that would not be enough in the end.

**Comment by panz3r** [comment]
Hi @alcesleo ,

Let me know if you find something I can help you with.

From what I understand, you are getting a tokens pair from another API and then injecting it into Keycloak, is that right?

> Even if I do get this to work, is it possible to set something in the `_app.tsx` based on an API request? I'm only trying to hard code in a token at this point but that would not be enough in the end.

To do this you just need to add a `getInitialProps` static method to the exported `App` from `_app.tsx` file, see NextJS docs [here](https://nextjs.org/docs/advanced-features/custom-app) for more info.

**Comment by alcesleo** [comment]
Will do, at least I know I'm not doing something entirely unsupported :) 

Yes exactly, a server is proxying to Keycloak, authenticating in a different way and simply forwarding the response from the Keycloak /token endpoint, and now I'm trying to tie it together to automatically log the user in in the browser.

I'll get back with the solution when and if I find it.

**Comment by alcesleo** [comment]
Regarding the `getInitialProps` - forgive me if I'm missing something obvious, but doesn't the call to `appWithKeycloak` need to be exported outside of the this?

**Comment by panz3r** [comment]
Hi @alcesleo ,

Yes, you are right.
A solution might be to move the `appWithKeycloak` inside the `render` method instead of exporting it directly.

```js
class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props
    return appWithKeycloak({
      realm: process.env.KEYCLOAK_REALM,
      url: process.env.KEYCLOAK_URL,
      clientId: process.env.KEYCLOAK_CLIENT_ID
    })(<Component {...pageProps} />)
  }
}

export default MyApp
```

**Comment by alcesleo** [comment]
Didn't know that could be done, looks good! I still haven't gotten it to accept the tokens yet, hopefully I have some time to debug it properly soon. Thank you for all the advice

**Comment by alcesleo** [comment]
Further adventures into this issue: I tried to move the `appWithKeycloak` call into the `render`-function as you suggested, I get the following error:

```
Error: Unknown element-like object type: Symbol(react.element). This is likely a bug in React. Please file an issue.
    at ReactDOMServerRenderer.render (/mnt/c/Development/.../.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3619:21)
    at ReactDOMServerRenderer.read (/mnt/c/Development/.../.../node_modules/react-dom/cjs/react-dom-server.node.development.js:3536:29)
    at renderToString (/mnt/c/Development/.../.../node_modules/react-dom/cjs/react-dom-server.node.development.js:4245:27)
    at render (/mnt/c/Development/.../.../node_modules/next/dist/next-server/server/render.js:81:16)
    at renderPage (/mnt/c/Development/.../.../node_modules/next/dist/next-server/server/render.js:346:16)
    at Object.ctx.renderPage (/mnt/c/Development/.../.../.next/server/static/development/pages/_document.js:1895:30)
    at Function.getInitialProps (/mnt/c/Development/.../.../.next/server/static/development/pages/_document.js:538:19)
    at Function.getInitialProps (/mnt/c/Development/.../.../.next/server/static/development/pages/_document.js:1905:87)
    at Object.loadGetInitialProps (/mnt/c/Development/.../.../node_modules/next/dist/next-server/lib/utils.js:59:29)
    at Object.renderToHTML (/mnt/c/Development/.../.../node_modules/next/dist/next-server/server/render.js:350:36)
    at <anonymous>
```

The object returned by `render` looks the following:

```
{ [Function: AppWithKeycloak]
  getInitialProps: [Function: getInitialProps],
  propTypes: { pageProps: [Function: bound checkType] },
  '$$typeof': Symbol(react.element),
  key: null,
  ref: null,
  props:
   { theme: { colors: [Object], fonts: [Object] },
     children:
      { '$$typeof': Symbol(react.element),
        type: [Object],
        key: null,
        ref: null,
        props: [Object],
        _owner: null,
        _store: {} } },
  _owner: null,
  _store: {} }
```

**Comment by panz3r** [comment]
Hi @alcesleo ,

Sorry for the late answer.

It seems like I'll need to add a method (much like `getInitialProps`) to allow passing dynamic `Keycloak` init options.

I'll add it as soon as possible and update this issue once it'll be released.

**Comment by alcesleo** [comment]
You respond quicker than anyone working for free could be expected ;-) I really appreciate your help! 

I think being able to set the token/refreshToken based on localStorage is probably the most common use case for this functionality.

**Comment by panz3r** [comment]
Hi @alcesleo ,

I just released `@react-keycloak/nextjs` version `1.0.0-alpha.15` with the new `Dynamic initConfig` feature.
See [here](https://github.com/panz3r/react-keycloak/blob/master/packages/nextjs/README.md#dynamic-react-keycloak-initconfig) for the related doc.

In short, you can now specify a static method `getKeycloakInitConfig` method inside your `_app.jsx` file to pass dynamic values for the `initConfig` of `KeycloakProvider`, like this
```ts
class MyApp extends App {
  /**
   * Pass additional dynamic initProps to Keycloak
   */
  static async getKeycloakInitConfig(ctx: AppContext) {
    console.log('MyApp - getKeycloakInitConfig', ctx)
    // Return an object with keycloak initConfig supported keys - see Keycloak docs
    return {
      token: 'test'
    }
  }

  render() {
    const { Component, pageProps } = this.props
    return <Component {...pageProps} />
  }
}

export default appWithKeycloak({
  realm: process.env.KEYCLOAK_REALM as string,
  url: process.env.KEYCLOAK_URL as string,
  clientId: process.env.KEYCLOAK_CLIENT_ID as string
})(MyApp)
```

Thanks again for your feedback and let me know if this helps you better achieve your desired use-case.

**Comment by alcesleo** [comment]
Nice work, thanks a lot! I think this is exactly what is needed from @react-keycloak/nextjs's perspective. 🙂 

I have investigated further in the meantime and doing it like this comes with a trade-off:

To get keycloak-js (which is the underlying library) to accept the token, you also have to set `checkLoginIframe: false` in the initConfig. Please correct me if I'm wrong, the behaviour I've observed is that if there is not a valid session cookie in the keycloak domain, the iframe will detect this and instantly log you out.

This essentially means that you're running without SSO - you have a valid access token and it should work properly on _this_ domain, but it will not detect a Single Sign-Out, and the cookies that need to be set for SSO (in the keycloak domain, which is probably not the same as your app) will not be present, so attempting to "stay logged in" moving to a different site with SSO will not be supported.

Another gotcha here is that in the newest version of keycloak-js at the time of writing, setting `checkLoginIframe: false` actually produces an error, this is a known bug in keycloak-js: https://issues.redhat.com/browse/KEYCLOAK-13064

**Comment by ApacheEx** [comment]
thank you @alcesleo 🥇 

I got exactly the same problem with initializing tokens from the backend for `@react-keycloak/web` and `checkLoginIframe: false` resolves the issue.
