### ISSUE TITLE
[SOLVED] TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by styk-tv** [panz3r/react-keycloak#54]
> TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined at validateString (internal/validators.js:125:11) at Object.join (path.js:1147:7)

SOLVED (if anyone is searching) that upgrading "react-scripts" from "3.3.0" to "^3.4.0"

ref: https://github.com/facebook/create-react-app/issues/8499#issuecomment-588597645

**Comment by panz3r** [comment]
Hi @styk-tv ,

Thanks for reporting this issue.

As per your ref, It seems to be more related to `create-react-app` than to `react-keycloak` so I'm going to close this issue.

Thanks again.

**Comment by styk-tv** [comment]
@panz3r posted here because none of the examples worked until i fixed above.

**Comment by panz3r** [comment]
@styk-tv , I see, thanks.

You are right about that, I'm working on the update of the various dependencies of the project but it's taking some time.

Thanks again.
