### ISSUE TITLE
NextJS refresh token undefined

### ISSUE THREAD

**Issue by mohux** [panz3r/react-keycloak#58]
When I try to call keycloak.updateToken(time) 

its not working, when I see the network I see that the API token is called with refresh_token: undefined

**Comment by panz3r** [comment]
Hi @mohux ,

Thanks for your feedback and sorry for the delay in my answer.

Can you please provide more details about what you are trying to achieve?
- What versions of `nextjs`, `keycloak-js` and `@react-keycloak/nextjs` are you using?
- When are you calling `keycloak.updateToken`?
- In which cases are you getting the error?

**Comment by mohux** [comment]
"@react-keycloak/nextjs": "^1.0.0-alpha.16",
    "keycloak-js": "^8.0.1",
    "next": "^9.2.0",


the issue was with keycloak-js 
i had to go to node_modules
and look for the updateToken
the function was calling undefined refresh token

fixed it by going to keycloak.js and adding this

``` 
const rt = kc.refreshToken;
``` 
at line 590 before exec function
and calling rt instead of kc.refreshToken idk why 




setInterval checking if token is still valid, if not, calling refreshToken if its still valid,
tried it on app.js and other pages

**Comment by panz3r** [comment]
Closing this issue since it's related to `keycloak-js` and not `@react-keycloak`.
