### ISSUE TITLE
`autoRefreshToken` is not exposed in web package

### ISSUE THREAD

**Issue by incik** [panz3r/react-keycloak#64]
Hi,
although you mention it is not recommended, I need to disable automatic refreshing of tokens.

I think that the intent was for it work like this:
`<KeycloakProvider keycloak={keycloak} autoRefreshToken={false}>`, because I can see that there is `autoRefreshToken` prop in `ProviderProps` in the `core` package (with that comment about it not being recommended). However this props is missing in `ProviderProps` in the `web` package, so TypeScript throws an error. And I was not successful in importing the provider directly from `core`.

So, I wonder how am I suppose to set this prop? Is this a bug or am I missing some principle of setting props to the provider? :/ 

Thanks!

**Comment by panz3r** [comment]
Hi @incik ,

Thanks for your feedback, I had a quick look and it seems that prop is just missing in the TS definitions of the `web` package but should work as expected.

I'll update them and publish an updated version as soon as possible.

**Comment by panz3r** [comment]
Hi @incik ,

Newly released version `2.1.0` of `@react-keycloak/web` package should fix your issue.

Let me know if it works so that I can close this issue.

**Comment by incik** [comment]
Hi, I was finally able to test it, and it works as advertised. Thank you! :-)
