### ISSUE TITLE
Sticky Tokens

### ISSUE THREAD

**Issue by monowai** [panz3r/react-keycloak#66]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is an issue or by design, but there seems to be an unnecessary refresh of a valid token when reloading a web page.

My hooks have `keycloak.token` in the dependency array (exhaustive depends lint check).  When the browser is is Refreshed (F5/Hot reload), the token changes (original->new) meaning the effect runs multiple times. 

**Describe the solution you'd like**
If the browser session id has not changed we should use the same auth token

**Additional context**
A service I'm integrating with has rate limiting in place and calling my intermediary service multiple times causes the `RateLimiter` to trip.  I can work around with caching, but in general, this is causing unnecessary network traffic and backend processing.

**Comment by panz3r** [comment]
Hi @monowai ,

Thanks for your feedback.

> My hooks have keycloak.token in the dependency array (exhaustive depends lint check). When the browser is is Refreshed (F5/Hot reload), the token changes (original->new) meaning the effect runs multiple times.

For what I can understand this refresh is triggered by how `keycloak-js` handle its `init` phase (and how `react-keycloak` integrate with it) until a successful `init` response the token available inside `react-keycloak` context is `undefined` and then receives the actual token on successful authentication (the `token` is retained by `ReactKeycloakProvider` to avoid calling `onTokens` event handler when token did not change).

 > If the browser session id has not changed we should use the same auth token

To "fix" this issue there are 2 available solutions I can think of:

- Try to use `LoadingComponent` to avoid loading the component tree until `keycloak-js` has been initialised (and thus avoid the initial `undefined` -> `token` transition on the hook.

- Cache `keycloak` tokens (something I won't recommend but also one of the first requested features of `react-keycloak` 😅 ) as discussed in issue #1 and #3 .

Another thing you can try is to use the `silentCheckSsoRedirectUri` setup and see if in this way `keycloak-js` can retain tokens by itself (see official docs for more details [here](https://www.keycloak.org/docs/latest/securing_apps/#_javascript_adapter))

Thanks again and let me know if this helps you.
