### ISSUE TITLE
External usage example

### ISSUE THREAD

**Issue by AAverin** [panz3r/react-keycloak#67]
**Is your feature request related to a problem? Please describe.**
Documentation mentioned that for external (advanced) usages we should import Keycloak directly from `keycloak.js`.
It is not clear which `keycloak.js` is it and how to exactly use it.

**Describe the solution you'd like**
It would be great to have some example on how can I use keycloak inside axios API calls that are done from redux middleware (kind of like saga)

**Comment by AAverin** [comment]
Suggested solution to import js function directly is a bit tricky with `gatsby` due to `window is not defined` error

**Comment by AAverin** [comment]
Would re-creating keycloak be enough?
```
const Keycloak = require('keycloak-js')
const keycloak = new Keycloak({
  realm: process.env.KEYCLOAK_REALM,
  url: process.env.KEYCLOAK_URL,
  clientId: process.env.KEYCLOAK_CLIENT_ID,
})
```
Will this `keycloak` be properly initialised already if I create it again later than KeycloakProvider got it's instance?

**Comment by boukmi** [comment]
I'm facing the same issue.
I need to access keykloak from a non-react file (a utility file). Do you have any code sample that shows how to do that?
Thank you

**Comment by panz3r** [comment]
Hi @boukmi ,

You can find a sample of how to do what you need by following the setup guide described on the [`@react-keycloak/web`](https://github.com/react-keycloak/react-keycloak/blob/master/packages/web/README.md#getting-started) README and in particular the [`External usage`](https://github.com/react-keycloak/react-keycloak/blob/master/packages/web/README.md#external-usage-advanced) section
