### ISSUE TITLE
keycloak is not initialized in hooks

### ISSUE THREAD

**Issue by AAverin** [panz3r/react-keycloak#68]
**Describe the bug**
In `createReactKeycloakContext` initialized is set to `false` and looks like it never becomes `true`.
When calling `keycloak.login()` I am getting that `adapter` property inside `keycloak.js` is undefined, that seems to be possible if keycloak wasn't initialized.

I am not sure if it's related to hooks `initialized` property at all though.

Use-case scenario:
- I am writing a PrivateRoute for Gatsby.js and am using `useKeycloak` similar to how it's shown in react-router examples. When being redirected back from keycloak authentication to my page I get `Cannot read property 'login' of undefined` pointing that `adapter` is undefined and keycloak isn't properly inited

KeycloakProvider is present in the hierarchy and some kind of keycloak is provided by `useKeycloak` with my realm settings. It's just doesn't seem to be properly initialized

**Comment by AAverin** [comment]
Could it be that `useKeycloak` returns before `componendDidMount` of KeycloakProvider finished it's init flow?

**Comment by AAverin** [comment]
Here is my PrivateRoute:
```
const PrivateRoute = ({ component: Component, location, ...rest }) => {

  const [keycloak, initialized] = useKeycloak()
  console.log('PrivateRoute', initialized, keycloak, keycloak.authenticated)
  if (!keycloak.authenticated && location.pathname !== `/login`) {
    keycloak.login()
    return null
  }

  return <Component {...rest} />
}
```

**Comment by AAverin** [comment]
I am following `gatsby` example and have put KeycloakProvider into `gatsby-browser.js` file.
I have attached `onEvent` callback with logs but it never seems to be executed

**Comment by AAverin** [comment]
My latest findings show that this could be somehow related to cors issues

**Comment by aelfric** [comment]
Disclaimer: I don't use this library myself. I just came here to see how the authors handled a particular keycloak problem we've brushed up against. 

They said, I'm pretty sure in your case you can fix your problem by adding 

```
if(!initialized){
    return <p>Loading...</p;
}
```
(Or some other suitable fallback component)

**Comment by AAverin** [comment]
I have tried doing that, but looks like my whole initialization fails due to CORS.
I have tried putting origin urls in keycloak admin panel, but it didn't help, still failes with cors request.

**Comment by AAverin** [comment]
So I'm back to square one.
I resolved CORS issues, at least I no longer see any errors in the console.
Still, keycloak is not initialized in hooks.

**Comment by AAverin** [comment]
So it looks like in Gatsby, KeycloakProvider never really inits.
I start getting at least `onReady` event if I do this and put it to gatsby-browser instead of the regular KecloakProvider
```
class TestKeycloakProvider extends KeycloakProvider {
  componentDidMount() {
    super.componentDidMount()
    console.log(`TestKeycloakProvider`, 'didMount', this)
    try {
      this.init()
    } catch (e) {
      console.log(e)
    }
  }
}
```

**Comment by AAverin** [comment]
The issue isn't yet resolved

**Comment by punithbm** [comment]
@panz3r  Hello, can you please check on this. We're also facing a similar issue and not able to identify a solution. We're getting keycloak is not initialized in the hooks on refreshing the page

**Comment by AAverin** [comment]
@punithbm The project I am using keycloak in is on pause now so I will need some time to refresh my memory.
This seem to have worked so far:
```
import React from 'react'
import { useKeycloak } from '@react-keycloak/web'

const PrivateRoute = ({ component: Component, ...rest }) => {
  const [keycloak, initialized] = useKeycloak()
  console.log('PrivateRoute', initialized, keycloak, keycloak.authenticated)

  if (!initialized) {
    return <></>
  }

  if (!keycloak.authenticated) {
    keycloak.login()
    return <></>
  }

  return <Component {...rest} />
}
```

**Comment by aelfric** [comment]
I didn't realize when I first commented on this issue that you were using Gatsby. I expect the issue is that your code is running during the server-side rendering phase and not in the browser. 

I have not used it myself, but I think for Gatsby you'd need to follow or borrow from the NextJS example provided in this repository. The essential thing is to wrap Keycloak initialization with a check for whether it's running in the browser. The recommended way to do that seems to be `if(typeof window !== 'undefined')`
