### ISSUE TITLE
Question: Is there a recommended/easy way to have public pages?

### ISSUE THREAD

**Issue by alcesleo** [panz3r/react-keycloak#69]
We are using NextJS with `onLoad: "login-required"` set in the `_app.tsx`. What would be the preferred way for having some pages being completely unauthenticated? 

Best regards

**Comment by alcesleo** [comment]
Rendering the `_error.tsx` page for example is a common use case for this.

**Comment by jannes-io** [comment]
@alcesleo we have a couple of apps in production with an anonymous zone. use `onLoad: 'check-sso'` instead.
This will check if there is a user session. If so => retrieve a token, if not => keycloak token will be undefined and you can use `keycloak.login()` to redirect to the KC login page if needed for restricted zones.

**Comment by alcesleo** [comment]
@jannes-io That seems to work! However, the content-page flashes before being redirected to the login page, is there any way to prevent that?

**Comment by alcesleo** [comment]
Also, where would you put the check for `keycloak.token`? I still would like the default behaviour to be like in `"login-required"` across the vast majority of our pages, and not add a check to every page component.

**Comment by jannes-io** [comment]
@alcesleo we made a custom abstraction of BrowserRouter which adds an optional "security" check to each route. When the route is accessed it will check this security parameter. If it isn't set it is considered to be a publicly accessible page, otherwise, check if the user token has the required client roles.

I would post examples but it's proprietary code so I can't share it.

**Comment by alcesleo** [comment]
Thank you for your help! It sounds like your solution might be cleaner but AFAIK BrowserRouter is not a thing in NextJS, at least by default. 

This is the solution I came up with for NextJS, it's not the least hacky code I've written, so if anyone knows a better way of doing this in NextJS please let me know. 

It does let me keep the default behaviour of `"login-required"` without having to change every single page and risking to forget to use the wrapper/superclass to make pages private (which is almost always the case for us).

Create a `LoginRequired.tsx` component:

```ts
import React from "react";
import { useKeycloak } from "@react-keycloak/nextjs";

interface LoginRequiredProps {
  children: React.ReactElement;
}
export const LoginRequired: React.FC<LoginRequiredProps> = ({ children }) => {
  const [keycloak] = useKeycloak();

  // Do not require login if the component has a truthy `public` prop
  if (!keycloak.token && !children.props?.public) {
    keycloak.login();

    // Do not render anything unless logged in
    return null;
  }

  return children;
};
```

Wrap the Component in `_app.tsx`:

```tsx
function MyApp({ Component, pageProps, cookies }: AppProps & InitialProps) {
  return (
    <SSRKeycloakProvider
      keycloakConfig={keycloakCfg}
      initConfig={keycloakInitCfg}
      persistor={Persistors.Cookies(cookies)}
    >
      <LoginRequired>
        <Component {...pageProps} />
      </LoginRequired>
    </SSRKeycloakProvider>
}
```

Then you can mark public pages as public by setting a `public: true` prop:

```ts
interface MyPublicPageProps {
  public: boolean;
}
const MyPublicPage: NextPage<MyPublicPageProps> = () => {
  return <h1>Public page</h1>
};

MyPublicPage.getInitialProps = () => {
  return { public: true };
};
```
