### ISSUE TITLE
ReactKeycloakHookResult returns a Keycloak.KeycloakInstance<"legacy"> in NextJS

### ISSUE THREAD

**Issue by alcesleo** [panz3r/react-keycloak#70]
**Describe the bug**

When using the `useKeycloak` hook in TypeScript in a NextJS project, it returns a `Keycloak.KeycloakInstance<"legacy">` instead of the `Keycloak.KeycloakInstance<"native">`

**To Reproduce**

Use the `useKeycloak` hook in TypeScript in a NextJS project and inspect the resulting type, the "legacy" type is defaulted since it is not specified.

**Expected behavior**

Return a `Keycloak.KeycloakInstance<"native">` or allow the user to specify the type.

**Additional context**

https://github.com/panz3r/react-keycloak/blob/3a528199b7199c4d08f805d22543d3303237af17/packages/nextjs/index.d.ts#L111-L117

**Comment by AAverin** [comment]
Did you configure keycloak instance in `KeycloakProvider`?
useKeycloak will return whatever was configured

**Comment by alcesleo** [comment]
Sorry for not specifying earlier, I am using NextJS. The `SSRKeycloakProvider` for NextJS doesn't include the `keycloak` attribute, which I think you are referring to, and I am not entirely clear how I would use that to change the internal keycloak-js promise type.

https://github.com/panz3r/react-keycloak/blob/5a236408e5c5eb6f875dcb4378700ace4178ce58/packages/nextjs/src/SSRKeycloakProvider.js#L64-L72

**Comment by panz3r** [comment]
Hi @alcesleo,

Thanks for your feedback and sorry for the late answer.

This error is quite strange, `Keycloak` TS typings were updated in version `9.0.2` to remove references to the `legacy` mode.

Which version of `keycloak-js` and `@react-keycloak/nextjs` are you using?

**Comment by alcesleo** [comment]
Spot on, I had upgraded to the latest `@react-keycloak/nextjs` - but not upgraded `keycloak-js`. Upgrading that solved the issue. Thanks a lot!
