### ISSUE TITLE
Accessing Keycloak token from getServerSideProps in NextJS app

### ISSUE THREAD

**Issue by aa-afk** [panz3r/react-keycloak#71]
New to NextJS and Keycloak so apologies for any ignorance in the below. This is just a question because I've hit a brick wall.

I've got a page in my NextJS app that utilises `getServerSideProps()` to fetch data from an API endpoint (to server-side render the page). The URL for said API endpoint requires an ID present in the `idTokenParsed` property on the client (when using the React hook or HOC approach). Is it possible to get this ID from the token on the server (aka, within the `getServerSideProps()` method)?

For context, I need something like:

```javascript
...
export async function getServerSideProps() {
    return { props: { data: await getData(ID_FROM_TOKEN_HERE) } } // on the server I can't use the hook to retrieve the token
}

export default ({ data }) => {
    const { keycloak } = useKeycloak()
    console.log(keycloak.idTokenParsed.dataId) // on the client it's fine
    ...
}
```

Thanks in advance!

**Comment by jakubdusek** [comment]
@aa-afk Do you found correct solution ? Thanks for responde :)

**Comment by aa-afk** [comment]
@jakubdusek I’m sorry I did not. I pursued a different implementation. Would be curious to know if there is a solution to this!
