### ISSUE TITLE
Safari browser keycloak refreshes constantly

### ISSUE THREAD

**Issue by aminmc** [panz3r/react-keycloak#72]
**Describe the bug**
When using the library in an app (even using the example project (react-navi)) on Safari the lib seems to refresh constantly. Not an issue in Chrome or Firefox

**To Reproduce**

1. Checkout project react-navi
2. Change keycloak config to 'login-required'
3. Open project in Safari
4. Constant refresh
5. Token expiry time 30mins

**Expected behavior**
Safari not constantly refreshing

**Screenshots**

![refresh](https://user-images.githubusercontent.com/290639/83322267-1dd70100-a24e-11ea-9535-8778e0b1b8af.gif)

**Desktop (please complete the following information):**

- OS: macOS
- Browser Safari
- Version 3.0.5 (15608.5.11)

**Comment by jannes-io** [comment]
@aminmc ,

Seems to be a Keycloak configuration issue. Just tested on macOS safari and it works fine here with 'login-required'.

Check that you are using the correct client and that the client is configured correctly (CORS, redirect_uri,...).

**Comment by aminmc** [comment]
@jannes-io yup...keycloak configuration issue...aka 'user error'!.  Thank you for investigating the issue.  Closing this issue now.

**Comment by lbarthon** [comment]
Hey @aminmc,
How have you fixed this ? I have a KeycloakProvider with `initConfig` set to `{ onLoad: 'login-required' }`, and it keeps refreshing
