### ISSUE TITLE
About No ‘Access-Control-Allow-Origin’ header is present on the requested resource.

### ISSUE THREAD

**Issue by uugan** [panz3r/react-keycloak#77]
I'm not sure if it's a bug of this library.
On confidential client it returns error like this. 

`Access to XMLHttpRequest at ‘http://{auth_server_ip}:8080/auth/realms/{clientId}/protocol/openid-connect/token’ from origin ‘http://localhost:3000’ has been blocked by CORS policy: No ‘Access-Control-Allow-Origin’ header is present on the requested resource.`

keycloak configuration:
![image](https://user-images.githubusercontent.com/601881/84898037-2bf3a100-b0d9-11ea-9b2a-6fbb5515a7c5.png)
changed web origin to * but nothing changes.

index.js source code example:

```javascript
let keycloak = Keycloak('/keycloak.json'); 
keycloak.init({ onLoad: 'login-required'}).success((auth) => {
    if (!auth) {
        window.location.reload();
    } else {
        console.info("Authenticated");
        keycloak.loadUserInfo().then(userInfo => {
            console.info(userInfo)
            //this.setState({name: userInfo.name, email: userInfo.email, id: userInfo.sub})
        });
    }
    ReactDOM.render(<Router><App /></Router>, document.getElementById('root'));
    localStorage.setItem("react-token", keycloak.token);
    localStorage.setItem("react-refresh-token", keycloak.refreshToken);
    setTimeout(() => {
        keycloak.updateToken(70).success((refreshed) => {
            if (refreshed) {
                console.debug('Token refreshed' + refreshed);
            } else {
                console.warn('Token not refreshed, valid for ' + Math.round(keycloak.tokenParsed.exp + keycloak.timeSkew - new Date().getTime() / 1000) + ' seconds');
            }
        }).catch(() => {
            console.error('Failed to refresh token');
        });
    }, 60000)
}).catch(() => {
    console.error("Authenticated Failed");
});
```

When I configure access type from confidential to public this code works. What is wrong with my configuration?

**Comment by panz3r** [comment]
Hi @uugan ,

It does not seem an issue with this module but more an issue with the setup of Keycloak , here the configuration I use for the example projects, I hopes it can help you.

<img width="737" alt="keycloak-react-test" src="https://user-images.githubusercontent.com/1754457/84946875-a1676d80-b0e9-11ea-9a41-25ffb365b9ec.png">

**Comment by uugan** [comment]
Hi @panz3r 
Ok. Then I will close this. I have few questions. Did you try with confidential mode? 
The reason is on my backend I'm checking/verifying bearer token from keycloak (introspection endpoint). Introspection endpoint is checkable from client with secret key. Is there any ideas how to verify bearer token (jwt) ?

**Comment by panz3r** [comment]
Hi @uugan ,

> Ok. Then I will close this. I have few questions. Did you try with confidential mode?

Unfortunately had no chance to test it out with `confidential` mode.

> The reason is on my backend I'm checking/verifying bearer token from keycloak (introspection endpoint). Introspection endpoint is checkable from client with secret key. Is there any ideas how to verify bearer token (jwt) ?

As per the Keycloak docs 

> It is recommended to use distinct clients in Keycloak to represent your frontend and backend.

so you should create a new client on `Keycloak` to be used by your backend code and integrate one of the available adapter ([here](https://www.keycloak.org/docs/latest/securing_apps/#_nodejs_adapter) the docs for the `NodeJS` one) then you can use the exposed method to do the checks on the token when you need to.

**Comment by punithbm** [comment]
Hello @panz3r  

I was using the client with Access Type - confidential and faced a similar issue. After going through comments here, I was able to resolve by setting client Access Type to the public. 

I just wanted to know is there any plan of supporting access type as confidential? Because we had a request to keep the access type of client as confidential only.

**Comment by panz3r** [comment]
Hi @punithbm ,

Thanks for your feedback.

> I just wanted to know is there any plan of supporting access type as confidential? Because we had a request to keep the access type of client as confidential only.

I think that this question should be asked on the official `keycloak-js` repo (`react-keycloak` does not apply any special behaviour when setting the `Access Type`).
