### ISSUE TITLE
Get role attributes

### ISSUE THREAD

**Issue by itsalb3rt** [panz3r/react-keycloak#79]
I was looking for if there is a way to get the attributes of a specific role that the user has assigned but I could not find the solution.
Any ideas ?

**Official documentation**
https://www.keycloak.org/docs/8.0/securing_apps/index.html#_javascript_adapter

**Comment by panz3r** [comment]
Hi @itsalb3rt ,

Thanks for your feedback, to retrieve the roles for the currently logged in user you can use an hook like this

```js
function useKeycloakUserRoles() {
  const [keycloak, kcInitialized] = useKeycloak();
  const roles = useMemo(() => {
    if (!kcInitialized) {
      return [];
    }

    return keycloak?.tokenParsed?.realm_access?.roles ?? [];
  }, [keycloak, kcInitialized]);

 return roles;
}
```

**Comment by itsalb3rt** [comment]
> Hi @itsalb3rt ,
> 
> Thanks for your feedback, to retrieve the roles for the currently logged in user you can use an hook like this
> 
> ```js
> function useKeycloakUserRoles() {
>   const [keycloak, kcInitialized] = useKeycloak();
>   const roles = useMemo(() => {
>     if (!kcInitialized) {
>       return [];
>     }
> 
>     return keycloak?.tokenParsed?.realm_access?.roles ?? [];
>   }, [keycloak, kcInitialized]);
> 
>  return roles;
> }
> ```

Thank you! this answer partially helps me, but i need the attributes of the roles, is there a way to get the attributes of a specific role?
