### ISSUE TITLE
No event or callback on the KeycloakProvider component when keycloak init fails

### ISSUE THREAD

**Issue by papy57** [panz3r/react-keycloak#80]
Hello,
I performed some tests with the react-router example and would like  to integrate your package to update an application soon.

This example works fine, but I'm facing an issue when the keycloak server does not respond. For exemple, when a timeout error occurs during the keycloak init method which is called by and when the KeycloakProvider component is mounted, the rendering is then freezed on the 'loading...' message.
It seems there is no way for the application to be aware when a keycloak error happened during the initialization phase.

After digging in the code, In my understanding, there is no try/catch when the keycloak.init method is called.
See react-keycloak/packages/core/src/provider.js
 line 59
 keycloak.init({ ...this.defaultInitConfig, ...initConfig })

Do you have a work-arround to solve this?
Could you produce a listener or any other solution to avoid this issue.

Thanks.

**Comment by panz3r** [comment]
Hi @papy57 ,

Thanks for your feedback and sorry for the late answer.

I just released a new version of the modules to include a new event `onInitError` which gets triggered when the call to `keycloak.init` fails.

You can listen to the events by setting the `onEvent` prop on `KeycloakProvider`.

Let me know if this helps you.

**Comment by papy57** [comment]
Hi @panz3r,
Thanks you for your reply.
This is a great news!

Regards.
