### ISSUE TITLE
Add support for onReady callback event

### ISSUE THREAD

**Issue by Blackburn29** [panz3r/react-keycloak#9]
A nice to have really. For analytics tracking in some cases this could be useful where you want to fire events based on if the user is authenticated or not on app-load.

**Comment by panz3r** [comment]
Hi @Blackburn29 ,

Thanks for your feedback, with the newly published `v6.0.4` of `react-keycloak` you should be able to achieve what you requested.

Using the `onEvent` handler prop of `KeycloakProvider ` you can attach a listener to receive events fired from `keycloak-js`. Refer to [README.md](https://github.com/panz3r/react-keycloak/blob/master/README.md) for more info.

**Comment by Bowfish** [comment]
Can you please publish an example of how I can catch the onAuthScuees event. I'm a bit lost.

**Comment by Blackburn29** [comment]
It should be passed to the `onEvent` prop of the provider. It's documented with an example in the readme
